apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickcv-frontend
  labels:
    app: quickcv-frontend
    track: {{ .Values.frontend.track | default "stable" }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: quickcv-frontend
      track: {{ .Values.frontend.track | default "stable" }}
  template:
    metadata:
      labels:
        app: quickcv-frontend
        track: {{ .Values.frontend.track | default "stable" }}
    spec:
      containers:
      - name: quickcv-frontend
        image: {{ .Values.frontend.image }}
        resources:
{{ toYaml .Values.frontend.resources | indent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5 