apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickcv-backend
spec:
  replicas: 2 # kustomize can patch this
  selector:
    matchLabels:
      app: quickcv-backend
  template:
    metadata:
      labels:
        app: quickcv-backend
    spec:
      containers:
      - name: quickcv-backend
        image: REPLACE_IMAGE # kustomize will patch this
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: ecr-secret