apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: quickcv-cluster
  region: us-east-1
  version: "1.27"

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    minSize: 1
    maxSize: 3