apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickcv-backend
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: quickcv-backend
        image: 376129850308.dkr.ecr.us-east-1.amazonaws.com/quickcv-backend:prod
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickcv-frontend
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: quickcv-frontend
        image: 376129850308.dkr.ecr.us-east-1.amazonaws.com/quickcv-frontend:prod
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5 