apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickcv-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: quickcv-backend
        image: 376129850308.dkr.ecr.us-east-1.amazonaws.com/quickcv-backend:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickcv-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: quickcv-frontend
        image: 376129850308.dkr.ecr.us-east-1.amazonaws.com/quickcv-frontend:latest 