name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      R2_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
      R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-1

      - name: Build Docker image
        run: |
          docker build --build-arg R2_ACCESS_KEY_ID=$R2_ACCESS_KEY_ID \
                       --build-arg R2_SECRET_ACCESS_KEY=$R2_SECRET_ACCESS_KEY \
                       --build-arg R2_ENDPOINT_URL=$R2_ENDPOINT_URL \
                       --build-arg R2_BUCKET_NAME=$R2_BUCKET_NAME \
                       --build-arg GOOGLE_API_KEY=$GOOGLE_API_KEY \
                       -t quickcv-backend ./backend

      - name: Push Docker image to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 376129850308.dkr.ecr.us-east-1.amazonaws.com/quickcv-backend:latest
          docker tag quickcv-backend:latest 376129850308.dkr.ecr.us-east-1.amazonaws.com/quickcv-backend:latest
          docker push 376129850308.dkr.ecr.us-east-1.amazonaws.com/quickcv-backend:latest

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster quickcv-backend-cluster-dev --service quickcv-backend-service-dev --force-new-deployment